###
//CREATE A PRODUCT
POST http://localhost:9000/api/product HTTP/1.1
Content-Type: application/json

{
    "code": 465462182,
    "name": "Parlante azul negro 3",
    "price": 22300,
    "entradas": 10
}

###
//FIND ALL
GET http://localhost:9000/api/product/getAll HTTP/1.1
Content-Type: application/json

###.
//FIND BY ID
GET http://localhost:9000/api/product/64757fa483a2a02c6b786cc8 HTTP/1.1
Content-Type: application/json

###
//UPDATE A PRODUCT
PUT http://localhost:9000/api/product HTTP/1.1
Content-Type: application/json

{
    "code": 46546218,
    "name": "Parlante azul negro 2.0",
    "price": 32300
}

###.
//DELETE BY ID
DELETE http://localhost:9000/api/product/64757fa483a2a02c6b786cc8 HTTP/1.1
Content-Type: application/json

###.
//DELETE ALL
DELETE http://localhost:9000/api/product HTTP/1.1
Content-Type: application/json